nginx:
  image: nginx
  links:
    - app
  volumes:
    - "./nginx_conf.d/nginx.conf:/etc/nginx/nginx.conf"
    - "./logs:/var/log/nginx"
  volumes_from:
    - datastore
  ports:
    - "8081:8081"

app:
  build: .
  links:
    - redis
  volumes_from:
    - datastore

redis:
  image: redis

datastore:
  build: datastore

unittest:
  build: .
  command: 'bash -c ''go test -v'''

build:
  build: .
  volumes:
    - "./dist:/tmp/dist"
    - "./sh:/tmp/sh"
  command: 'bash /tmp/sh/build.sh'
